# Asigna un nombre al proyecto para evitar colisiones.
name: "agentes"

services:
  chat_app:
    # Construye la imagen a partir del dockerfile en el directorio actual.
    build:
      context: .
      dockerfile: dockerfile
    # Nombra la imagen construida para referencia futura.
    image: agentes-app:latest
    container_name: agentes_app
    restart: unless-stopped
    ports:
      - "8501:8501"
    # Carga las variables de entorno desde el archivo .env.
    env_file:
      - .env
    # Monta los volúmenes.
    volumes:
      # Monta el código fuente actual para hot-reloading durante el desarrollo.
      - .:/app
      # Usa un volumen nombrado para persistir la base de datos.
      - app_data:/app/data
    # Usa el healthcheck para determinar la salud del contenedor.
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8501/_stcore/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

# Define el volumen nombrado que Docker gestionará.
# Esta sección debe estar al nivel raíz del archivo.
volumes:
  app_data: